apiVersion: cpe.cogadvisor.io/v1
kind: Benchmark
metadata:
  name: mpigloo
  namespace: default
spec:
  benchmarkOperator:
    name: mpi
    namespace: default
  benchmarkSpec: |
    slotsPerWorker: 1
    cleanPodPolicy: Running
    mpiReplicaSpecs:
      Launcher:
        replicas: 1
        template:
          metadata:
            annotations:
              k8s.v1.cni.cncf.io/networks: multi-nic-sample
          spec:
            containers:
            - image: uk.icr.io/satellite/gloo:mpibench
              name: gloo-master
              command:
              - mpirun
              - --allow-run-as-root
              - -np
              - "2"
              - /benchmark
              - --threads
              - {{ .threads }}
              - --transport
              - tcp
              - --tcp-device
              - {{ .dev }}
              - --no-verify
              - {{ .test }}
            imagePullSecrets:
            - name: gloo-icr-io
      Worker:
        replicas: 2
        template:
          metadata:
            annotations:
              k8s.v1.cni.cncf.io/networks: multi-nic-sample
          spec:
            affinity:
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                      - key: mpi_job_name
                        operator: In
                        values:
                        - mpigloo
                    topologyKey: kubernetes.io/hostname
            containers:
            - image: uk.icr.io/satellite/gloo:mpibench
              name: gloo-worker
            imagePullSecrets:
            - name: gloo-icr-io
  iterationSpec:
    sequential: true
    configurations:
      - name: test
        values:
        - allreduce_ring
        - allreduce_ring_chunked
        - allreduce_halving_doubling
        - allreduce_bcube
    iterations:
      - name: threads
        values:
        - "2"
        - "4"
        - "8"
      - name: dev
        values:
        - net1-0,net1-1,net1-2,net1-3
        - net1-0,net1-1,net1-2
        - net1-0,net1-1
        - net1-0
  repetition: 5
  interval: 60
  parserKey: gloo