apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpe-parser
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpe-parser
  template:
    metadata:
      labels:
        app: cpe-parser
    spec:
      containers:
        - name: cpe-parser
          image: ghcr.io/ibm/cpe-operator/parser:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cpe-parser
spec:
  selector:
    app: cpe-parser
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080