name: Build and push controller

on:
  push:
    paths:
      - controllers/**
      - api/**
      - ./main.go
      - ./go.mod
      - config/**
      - ./Dockerfile
      - ./bundle.Dockerfile
      - ./Makefile

env:
  IMAGE_VERSION: '0.0.1'

jobs:    
  build-push-controller:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}/cpe/operator-controller
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.0'
      - name: Tidy
        run: |
          go mod tidy
          make generate fmt vet
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push controller
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:v${{ env.IMAGE_VERSION }}
          file: ./Dockerfile
      - name: Build and push controller (dev)
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:dev
          file: ./Dockerfile