name: Build and push parser

on:
  push:
    paths:
      - .github/workflows/**
      - cpe-parser/**

env:
  IMAGE_VERSION: '0.0.1'

jobs:    
  build-push-parser:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/cpe-parser
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.0'
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push parser
        uses: docker/build-push-action@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          context: cpe-parser
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:v${{ env.IMAGE_VERSION }}
          file: ./cpe-parser/Dockerfile
      - name: Build and push parser (dev)
        uses: docker/build-push-action@v2
        if: ${{ github.ref != 'refs/heads/main' }}
        with:
          context: cpe-parser
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:dev
          file: ./cpe-parser/Dockerfile